// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"ZZZ_JumpToDestination","status":true,"description":"(v1.1)瞬移至目的地","parameters":{"瞬移模式的绑定的开关id":"1"}},
{"name":"windows","status":true,"description":"","parameters":{}},
{"name":"對話居中","status":true,"description":"","parameters":{}},
{"name":"TitleNewGameOnly","status":true,"description":"[ ver.2.1.0 ]讓標題畫面直接開始遊戲","parameters":{"startString":"點擊開始","font":"","fileExistAction":"2","soundEffect":"{\"name\":\"\",\"volume\":\"90\",\"pitch\":\"100\",\"pan\":\"0\"}","adjustY":"0"}},
{"name":"skiptitle","status":true,"description":"Skip Title.","parameters":{"Test Only":"false"}}
];
